In [1]:
from datetime import datetime
print(f'Päivitetty {datetime.now().date()} / Aki Taanila')

Päivitetty 2026-10-22 / Aki Taanila

**Ajoneuvojen avoin data** sisältää kaikkien liikennekäytössä olevien ajoneuvojen rekisteröinti-, hyväksyntä- ja teknisiä tietoja Traficomin ylläpitämästä liikenneasioiden rekisteristä. Datan laajuus on useita miljoonia rivejä, joten sitä ei voi ladata suoraan esimerkiksi taulukkolaskentaohjelmaan. Säännöllisesti päivittyvä data ja sen kuvaus löytyy osoitteesta:

https://tieto.traficom.fi/fi/tietotraficom/avoin-data

Datan voi ladata zip-pakettina osoitteesta:

https://opendata.traficom.fi/Content/Ajoneuvorekisteri.zip

Poimin datasta tiedot vuoden 2020 alusta eteenpäin rekisteröidyistä henkilöautoista. Otan mukaan vain osan muuttujista. Tallennan poimitun datan myöhempää käyttöä varten. Tallennettu data on sen kokoinen että sen voi avata tarvittaessa myös Exceliin.

**Koodin suoritus kestää kauan, koska ison datan lataaminen netistä on hidasta**. Sen jälkeen kun data (Ajoneuvoreksiteri.zip) on ladattu koneelle, niin sen lataamiseen liittyvää koodisolua ei tarvitse enää uudelleen suorittaa ellet halua hakea uudempaa versiota datasta.

In [2]:
# Ajoneuvorekisteri.zip -tiedoston lataaminen samaan hakemistoon tämän muistion kanssa
# Tämän solun suoritus kestää kauan, koska ladattava data on iso!

import requests
url = "https://opendata.traficom.fi/Content/Ajoneuvorekisteri.zip"
r = requests.get(url)
with open("Ajoneuvorekisteri.zip",'wb') as file:
    file.write(r.content)

In [3]:
import pandas as pd

In [4]:
# Mukaan otettavat muuttujat
cols = ['ajoneuvoluokka', 'ensirekisterointipvm', 'vari', 'korityyppi', 'omamassa', 
        'ajonKokPituus', 'ajonLeveys', 'ajonKorkeus', 'kayttovoima', 'suurinNettoteho', 
        'sahkohybridi', 'sahkohybridinluokka', 'merkkiSelvakielinen','mallimerkinta', 
        'vaihteisto', 'kaupallinenNimi', 'kunta', 'matkamittarilukema']

# Datan avaus (pandas osaa purkaa zip-paketin)
# Merkistökoodaus (encoding) löytyy datan kuvauksesta
df = pd.read_csv('Ajoneuvorekisteri.zip', sep=';', encoding='ISO8859-1', usecols=cols, low_memory=False)

In [5]:
# Tietoa muuttujista
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5296749 entries, 0 to 5296748
Data columns (total 18 columns):
 #   Column                Dtype
---  ------                -----
 0   ajoneuvoluokka        str
 1   ensirekisterointipvm  str
 2   vari                  str
 3   korityyppi            str
 4   omamassa              float64
 5   ajonKokPituus         float64
 6   ajonLeveys            float64
 7   ajonKorkeus           float64
 8   kayttovoima           str
 9   suurinNettoteho       float64
 10  sahkohybridi          object
 11  sahkohybridinluokka   float64
 12  merkkiSelvakielinen   str
 13  mallimerkinta         str
 14  vaihteisto            str
 15  kaupallinenNimi       str
 16  kunta                 float64
 17  matkamittarilukema    float64
dtypes: float64(8), object(1), str(9)
memory usage: 727.4+ MB

In [6]:
# Poimitaan datasta vain henkilöautot (ajoneuvoluokat M1 ja M1G)
df = df[df['ajoneuvoluokka'].isin(['M1', 'M1G'])]

In [7]:
# Varmistetaan, että päivämäärät tunnistuvat päivämääriksi
df['ensirekisterointipvm'] = pd.to_datetime(df['ensirekisterointipvm'], format='%d.%m.%Y')

In [8]:
# Rajoitutaan vuoden 2020 alusta lähtien rekisteröityihin
df = df[df['ensirekisterointipvm']>'2020-01-01'].sort_values('ensirekisterointipvm')

In [9]:
# Tallennus csv-muotoon
df.to_csv('autot.csv', index=False)

In [10]:
# Näytetään tulosteissa kaikki sarakkeet
pd.set_option.display_columns = None
df

,ajoneuvoluokka,ensirekisterointipvm,vari,korityyppi,omamassa,ajonKokPituus,ajonLeveys,ajonKorkeus,kayttovoima,suurinNettoteho,sahkohybridi,sahkohybridinluokka,merkkiSelvakielinen,mallimerkinta,vaihteisto,kaupallinenNimi,kunta,matkamittarilukema
4105414,M1,2020-01-02,0,AC,1395.0,4496.0,1841.0,1624.0,01,110.0,False,NaN,Skoda,KAROQ Farmari (AC) 4ov 1498cm3 A,2,KAROQ,580.0,73354.0
4119024,M1,2020-01-02,0,AA,1670.0,4885.0,1840.0,1445.0,01,131.0,True,2.0,Toyota,TOYOTA CAMRY Sedan (AA) 4ov 2487cm3,3,TOYOTA CAMRY,743.0,95073.0
3917934,M1,2020-01-02,2,AB,1345.0,4310.0,1800.0,1457.0,01,103.0,False,NaN,Kia,Ceed Viistoperä (AB) 5ov 1353cm3 A,2,Ceed,543.0,82209.0
4098012,M1,2020-01-02,9,AC,1794.0,4838.0,1870.0,1604.0,02,133.0,False,NaN,Volvo,XC70 Farmari (AC) 4ov 2400cm3 A,2,XC70,288.0,220635.0
4070098,M1,2020-01-02,8,AA,1455.0,4562.0,1796.0,1454.0,02,85.0,False,NaN,Mercedes-Benz,A 180 d Sedan (AA) 4ov 1461cm3 A,2,A 180 d,400.0,151468.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5238956,M1,2026-06-30,8,AB,2430.0,4840.0,2008.0,1534.0,04,NaN,False,NaN,Polestar,Polestar 4 Viistoperä (AB) 5ov,8,Polestar 4,108.0,NaN
5238643,M1,2026-06-30,0,AF,1452.0,4355.0,1806.0,1582.0,01,79.0,True,2.0,Honda,HR-V Monikäyttöajoneuvo (AF) 5ov 1498cm3 A,2,HR-V,285.0,NaN
5237754,M1,2026-06-30,9,AF,1572.0,4395.0,1795.0,1660.0,04,NaN,False,NaN,Citroen,e-C3 AIRCROSS Monikäyttöajoneuvo (AF) 5ov A,2,e-C3 AIRCROSS,853.0,NaN
5274645,M1,2026-06-30,2,AF,1893.0,4510.0,1865.0,1650.0,01,132.2,True,1.0,Hyundai,TUCSON Monikäyttöajoneuvo (AF) 5ov 1598cm3 A,2,TUCSON,91.0,63494.0
5296746,M1,2026-06-30,9,SA,2962.0,6985.0,2215.0,2900.0,02,125.0,False,NaN,Hymer,ML-T 580 Xperience Matkailuauto (SA) 3ov 1950c...,2,ML-T 580 Xperience,272.0,259.0

In [11]:
# Värit selviävät datan kuvauksesta
varit = ['Musta', 'Ruskea (beige)', 'Punainen', 'Oranssi','Keltainen', 'Vihreä', 'Sininen',
        'Violetti', 'Harmaa', 'Valkoinen', 'Monivär.', 'Hopea', 'Turkoosi']

In [12]:
# Kuinka suosittuja ovat eri värit olleet?
df1 = pd.crosstab(df['vari'], 'f')
df1.columns.name = ''

# Sijoitan värien nimet indeksiin, jossa alunperin on värien koodit
df1.index = varit

# Värit suosituimmuusjärjestyksessä
df1.sort_values('f', ascending = False)

                     f
Valkoinen       193192
Harmaa          175054
Musta           158235
Sininen          88194
Punainen         60796
Hopea            34380
Ruskea (beige)   22139
Vihreä           17038
Oranssi           7697
Keltainen         6639
Monivär.          3611
Violetti          1159
Turkoosi           595

In [13]:
# 20 suosituinta merkkiä
df2 = pd.crosstab(df['merkkiSelvakielinen'], 'f').nlargest(20, 'f' )
df2.columns.name = ''
df2

                          f
merkkiSelvakielinen
Toyota               102063
Volvo                 81599
Volkswagen, VW        72044
Mercedes-Benz         67539
Skoda                 60713
BMW                   51977
Kia                   48453
Audi                  33949
Tesla                 33524
Ford                  28639
Hyundai               20915
Nissan                20711
Opel                  13577
Peugeot               13160
Mitsubishi            12983
Polestar              12109
Renault                9819
Citroen                7894
Mazda                  6479
Seat                   5841

Jotkin automerkit saattavat esiintyä tietokannassa useilla eri nimillä. Esimerkiksi Volkswagen esiintyy ainakin kahdella eri nimellä (Volkswagen ja Volkswagen, VW). Seuraavassa yhdistän molemmat saman nimen alle.

In [14]:
df['merkkiSelvakielinen'] = df['merkkiSelvakielinen'].replace({'Volkswagen, VW':'Volkswagen'})
df3 = pd.crosstab(df['merkkiSelvakielinen'], 'f').nlargest(20, 'f' )
df3.columns.name = ''
df3

                          f
merkkiSelvakielinen
Toyota               102063
Volvo                 81599
Volkswagen            76579
Mercedes-Benz         67539
Skoda                 60713
BMW                   51977
Kia                   48453
Audi                  33949
Tesla                 33524
Ford                  28639
Hyundai               20915
Nissan                20711
Opel                  13577
Peugeot               13160
Mitsubishi            12983
Polestar              12109
Renault                9819
Citroen                7894
Mazda                  6479
Seat                   5841

In [15]:
# Rajoitutaan vai suosituimpiin merkkeihin
df_suositut = df[df['merkkiSelvakielinen'].isin(df3.index)]

# Värit suosituilla merkeillä
df4 = pd.crosstab(df_suositut['merkkiSelvakielinen'], df_suositut['vari'])

# Sijoitan värien nimet sarakkeisiin
df4.columns = varit

# Värjätään kunkin merkin kohdalla suosituin väri
df4.style.highlight_max(color='lightgreen', axis=1)

## Lisätietoa

Data-analytiikka Pythonilla https://tilastoapu.wordpress.com/python/